{% extends "main.phtml" %}
{% block css %}
<link href="{{ url.getStatic('plugins/kindeditor/themes/default/default.css') }}" rel="stylesheet">
{% endblock %}
{% block content %}
<ol class="breadcrumb">
  <li><a href="{{ url.get('/Backend') }}">首页</a></li>
  <li><a href="{{ url.get('index') }}">公众号管理</a></li>
  <li class="active">授权</li>
</ol>

<form role="form" class="form-horizontal" method="post">
    <div class="form-group">
        <label class="col-sm-2 control-label">公众号名</label>
        <div class="col-sm-10">
            <input type="text" name="username" class="form-control inline-block" placeholder="输入授权的用户名" style="max-width: 400px" maxlength="13" required="required"/>
            <em>13个字以内</em>
        </div>
    </div>
    
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">提交</button>
        </div>
    </div>
    
</form>

<h3>已授权的用户</h3>
<table class="table index_wechat_table small">
    <thead>
        <tr>
            <th>uid</th>
            <th>用户名</th>
            <th>操作</th>
        </tr>
    </thead>
    {% for user in list %}
    <tr>
        <td>{{ user.id }}</td>
        <td>{{ user.username }}</td>
        <td><a href="javascript:void(0);" onclick="authorize_cancel('{{ info.id }}','{{ user.id }}',this)">取消</a></td>
    </tr>
    {% endfor %}
    
</table>
{% endblock %}

{% block javascript %}
<script>window.currentnav='nav-1';</script>
<script>
    function authorize_cancel(wechat_id,uid,e)
    {
        $.ajax({
            url:"{{ url('cancelAuth') }}",
            dataType:"json",
            type:"post",
            data:{id:wechat_id,uid:uid},
            error:function(){alert('网络错误，请重试')},
            success:function(res){
                if (res.status && res.status == "1") {
                    $(e).parent().parent("tr").remove();
                } else {
                    
                }
            }
        });
    }
</script>
{% endblock %}