{% extends "main.phtml" %}
{% block content %}
{{ partial('aside',['actived':'g2.c2']) }}
<section class="content">
    {% for rule in list %}
    <div class="panel panel-default wx-reply">
        <div class="panel-heading wx-reply-heading">
            <div class="pull-left"><b>规则:</b> {{ rule.title }}</div>
            <div class="open">展开<span class="caret"></span></div>
        </div>
        <div class="panel-body">
            <div class="wx-reply-keywords">
                <div class="wx-reply-keywords-overview">
                    <strong>关键词</strong>
                    {% for keyword in rule.keywords %}
                    <em>{{ keyword.keyword }}</em>
                    {% endfor %}
                </div>
            </div>
            <div class="wx-reply-details">
                详细信息
            </div>
        </div>
    </div>
    {% endfor %}
    <button type="button" data-toggle="modal" data-target="#wx-reply-newrule" class="btn btn-primary">添加规则</button>
</section>
<!--弹出层：创建新规则-->
<div class="modal fade" id="wx-reply-newrule">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">创建新规则</h4>
            </div>
            <form role="form" id="wx-reply-newrule-form" action="{{ url('addRule') }}" method="post">
                <input type="hidden" name="newrule[type]" value="0"/>
                <div class="modal-body">
                        <div class="form-group">
                            <label>规则名：</label>
                            <input type="text" class="form-control" name="newrule[title]" required/>
                            <p class="help-block">10字以内</p>
                        </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn" onclick="reset();">重置</button>
                    <button type="submit" class="btn btn-primary">提交</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% endblock %}
{% block javascript %}
<script>window.currentnav='nav-99';</script>
<script>
    $(function(){
        //规则列表点击展开事件
        $(".wx-reply").each(function(i){
            var p = $(this);
            var heading = p.find('.wx-reply-heading');
            heading.on('selectstart',function(){return false});
            heading.click(function(){
                p.find('.wx-reply-keywords').toggle();
                p.find('.wx-reply-details').toggle();
            });
        });
        //end
        
        //弹出层区域
        var form = $("#wx-reply-newrule-form");
        //可拖动
        $("#wx-reply-newrule").find(".modal-dialog").draggable();
        //提交事件
        form.submit(function(e){
            e.preventDefault();
            $(this).ajaxSubmit({
                type:"post",
                error:function(){
                    alert('网络错误，请重试');
                },
                success:function(res){
                    if (res != "ok") {
                        alert(res);
                        return false;
                    }
                    //后台添加成功，刷新页面
                    window.location.reload();
                }
            });
        })
        //end
    });
</script>
{% endblock %}
