{% extends "main.phtml" %}
{% block content %}
{{ partial('aside',['actived':'g2.c2']) }}
<section class="content">
    <ol class="breadcrumb">
      <li><a href="{{ url.get('/Backend') }}">首页</a></li>
      <li class="active">规则列表</li>
    </ol>
    <section class="toolbar">
        <button type="button" class="btn btn-primary" onclick="wxReplyAdd()">添加新规则</button>
    </section>
    <table class="table small">
        <thead>
            <tr>
                <th>id</th>
                <th>规则名</th>
                <th>关键词</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            {% for rule in list %}
            <tr>
                <td>{{ rule.id }}</td>
                <td>{{ rule.title }}</td>
                <td>
                {% if keywords[rule.id] is defined %}
                    {% for keyword in keywords[rule.id] %}
                    {{ keyword.keyword }}
                    {% endfor %}
                {% endif %}
                </td>
                <td>
                    <a href="{{ url('edit',['id':rule.id]) }}">编辑</a> 删除
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</section>
<div style="display:none;" id="modal-newreply" title="新建规则">
    <form method="post" action="{{ url('add') }}">
        <div class="form-group">
            <label>规则名</label>
            <input type="text" class="form-control" name="rule[title]" placeholder="20字以内" maxlength="20" required/>
        </div>
    </form>
</div>
{% endblock %}
{% block javascript %}
<script>window.currentnav='nav-99';</script>
<script type="text/javascript">
    var formNewreply = $("#modal-newreply form:first");
    formNewreply.on('submit',function(e){
        e.preventDefault();
        formNewreply.ajaxSubmit({
            type:'post',
            dataType:"json",
            success:function(res){
                if (typeof(res)=='object') {
                    if (res.status == 0) {
                        $.wxAlert(res.msg);
                    } else {
                        window.location.href = "{{ url('edit') }}?id="+res.data.id;
                    }
                } else {
                    $.wxAlert('添加失败');
                }
                formNewreply[0].reset();
            }
        });
    })
    function wxReplyAdd()
    {
        $("#modal-newreply").dialog({
            resizable:false,
            position:{my:'center','at':'top+200'},
            buttons:[
                {
                    text:'确定',
                    click:function(){
                        formNewreply.trigger('submit');
                        $(this).dialog("destroy");
                    }
                }
            ]
        });
    }
</script>
{% endblock %}
