<ol class="breadcrumb">
  <li><a href="<?=$this->url->get('Backend');?>">首页</a></li>
  <li><a href="<?=$this->url->get('Backend/wechat');?>">公众号</a></li>
  <li class="active">新增</li>
</ol>
<form role="form">
    <div class="form-group">
        <label for="exampleInputEmail1">微信号</label>
        <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email" style="max-width: 400px">
    </div>
    <div class="form-group">
        <label>类型</label>
        <select class="form-control" style="max-width: 100px">
            <option>订阅号</option>
            <option>服务号</option>
        </select>
    </div>
    <div class="form-group">
        <label>认证</label>
        <select class="form-control" style="max-width: 100px">
            <option>未认证</option>
            <option>已认证</option>
        </select>
    </div>
    <div class="form-group">
        <label for="exampleInputFile">Logo</label>
        <input type="file" id="exampleInputFile">
        <p class="help-block">你公众号的头像.</p>
    </div>
    <button type="submit" class="btn btn-default">提交</button>
</form>