{% extends "main.phtml" %}
{% block css %}
<link href="{{ url.get('plugins/kindeditor/themes/default/default.css') }}" rel="stylesheet">
{% endblock %}
{% block content %}
<ol class="breadcrumb">
  <li><a href="{{ url.get('Backend') }}">首页</a></li>
  <li><a href="{{ url.get('Backend/wechat') }}">公众号管理</a></li>
  <li class="active">编辑</li>
</ol>
<form role="form" class="form-horizontal" method="post" action="{{ url('Backend/wechat/update') }}">
    <input type="hidden" name="wechat[id]" value="{{ info.id }}"/>
    <div class="bg-info">
        <div class="form-group">
            <label class="col-sm-2 control-label">Token</label>
            <div class="col-sm-10">
                <span class="help-block"> {{ info.token }}</span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">URL</label>
            <div class="col-sm-10">
                <span class="help-block"> {{ url.getStatic('api/weixin/'~info.token) }}</span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">提示</label>
            <div class="col-sm-10">
                <span class="help-block"><p class="text-danger">使用Token和URL去微信公众平台后台开启<b>开发者模式</b>，得到<b>AppId</b>和<b>AppSecret</b>。</p></span>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">公众号名</label>
        <div class="col-sm-10">
            <input type="text" name="wechat[name]" value="{{ info.name }}" class="form-control inline-block" placeholder="请输入你的公众号名称" style="max-width: 400px" maxlength="13" required="required"/>
            <em>13个字以内</em>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">账号类型</label>
        <div class="col-sm-10">
            {{ selectStatic(['wechat[type]',['0':'订阅号','1':'服务号'],'style':'max-width: 100px','value':info.type,'class':'form-control']) }}
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">认证情况</label>
        <div class="col-sm-10">
            {{ selectStatic(['wechat[verified]',['0':'未认证','1':'已认证'],'style':'max-width: 100px','value':info.verified,'class':'form-control']) }}
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">头像</label>
        <div class="col-sm-10">
            <img src="{{ url.getStatic(info.avatar) }}" id="logo-preview" style="max-width: 80px;max-height: 80px;"/>
            <input type="hidden" id="k-url1" name="wechat[avatar]" value="{{ info.avatar }}"/>
            <input type="button" class="btn btn-primary" value="选择图片" id="k-image1">
            <em>建议使用公众号头像</em>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">AppId</label>
        <div class="col-sm-10">
            <input type="text" name="wechat[appid]" value="{{ info.appid }}" class="form-control inline-block" placeholder="请输入开发者模式下的appid" style="max-width: 400px" maxlength="20" required/>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">AppSecret</label>
        <div class="col-sm-10">
            <input type="text" name="wechat[appsecret]" value="{{ info.appsecret }}" class="form-control inline-block" placeholder="请输入开发者模式下的appsecret" style="max-width: 400px" maxlength="32" required/>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">提交</button>
        </div>
    </div>
    
</form>

{% endblock %}

{% block javascript %}
<script charset="utf-8" src="{{ url.get('plugins/kindeditor/kindeditor-all-min.js') }}"></script>
<script>
    KindEditor.ready(function(K) {
        var editor = K.editor({
            allowFileManager : false,
            uploadJson : "{{ url.get('Backend/upload/image') }}"
        });
        
        K('#k-image1').click(function() {
            editor.formatUploadUrl = false;
            editor.loadPlugin('image', function() {
                    editor.plugin.imageDialog({
                            imageUrl : K('#k-url1').val(),
                            clickFn : function(url, title, width, height, border, align) {
                                    K('#k-url1').val(url);
                                    if(!/^http:/.test(url)){
                                        url = '{{ url.getStaticBaseUri() }}'+url;
                                    }
                                    K('#logo-preview').attr('src',url);
                                    editor.hideDialog();
                            }
                    });
            });
        });

    });
</script>

<script>window.currentnav='nav-1';</script>
{% endblock %}