{% extends "main.phtml" %}
{% block css %}
<link href="{{ url.get('plugins/kindeditor/themes/default/default.css') }}" rel="stylesheet">
{% endblock %}
{% block content %}
<ol class="breadcrumb">
  <li><a href="{{ url.get('Backend') }}">首页</a></li>
  <li><a href="{{ url.get('Backend/wechat') }}">公众号管理</a></li>
  <li class="active">编辑</li>
</ol>
<form role="form" class="form-horizontal" method="post" action="{{ url('Backend/wechat/update') }}">
    <div class="form-group">
        <label class="col-sm-2 control-label">token</label>
        <div class="col-sm-10">
            <span class="help-block">{{ info.token }}</span>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">公众号</label>
        <div class="col-sm-10">
            <span class="help-block">{{ info.name }}</span>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">账号类型</label>
        <div class="col-sm-10">
            <select class="form-control" name="wechat[type]"  style="max-width: 100px">
                <option value="0">订阅号</option>
                <option value="1">服务号</option>
            </select>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">认证情况</label>
        <div class="col-sm-10">
            <select class="form-control" name="wechat[verified]"  style="max-width: 100px">
                <option value="0">未认证</option>
                <option value="1">已认证</option>
            </select>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">头像</label>
        <div class="col-sm-10">
            <img src="" id="logo-preview" style="max-width: 80px;max-height: 80px;"/>
            <input type="hidden" id="k-url1" name="wechat[avatar]" class="form-control inline" readonly/>
            <input type="button" class="btn btn-primary" value="选择图片" id="k-image1">
            <em>建议使用公众号头像</em>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">提交</button>
        </div>
    </div>
    
</form>

{% endblock %}

{% block javascript %}
<script charset="utf-8" src="{{ url.get('plugins/kindeditor/kindeditor-all-min.js') }}"></script>
<script>
    KindEditor.ready(function(K) {
        var editor = K.editor({
            allowFileManager : false,
            uploadJson : "{{ url.get('Backend/upload/image') }}"
        });
        
        K('#k-image1').click(function() {
            editor.formatUploadUrl = false;
            editor.loadPlugin('image', function() {
                    editor.plugin.imageDialog({
                            imageUrl : K('#k-url1').val(),
                            clickFn : function(url, title, width, height, border, align) {
                                    K('#k-url1').val(url);
                                    if(!/^http:/.test(url)){
                                        url = '{{ url.getBaseUri() }}'+url;
                                    }
                                    K('#logo-preview').attr('src',url);
                                    editor.hideDialog();
                            }
                    });
            });
        });

    });
</script>
{% endblock %}
{% block javascript %}
<script>window.currentnav='nav-1';</script>
{% endblock %}