{% extends "main.phtml" %}
{% block content %}
<ol class="breadcrumb">
  <li><a href="<?=$this->url->get('Backend');?>">首页</a></li>
  <li class="active">公众号管理</li>
</ol>

<section class="toolbar">
    <a class='btn btn-primary' href="<?=$this->url->get('Backend/wechat/add');?>">添加公众号</a>
</section>

<table class="table index_wechat_table small">
    <thead>
        <tr>
            <th>Logo</th>
            <th>公众号</th>
            <th>token</th>
            <th>属性</th>
            <th>操作</th>
        </tr>
    </thead>

    <tr>
        <td><img src="http://localhost/phpmyadmin/themes/pmahomme/img/logo_left.png"/></td>
        <td>西祠每日精选</td>
        <td>sdfffe1123</td>
        <td>订阅号 <span class="label label-default">未认证</span></td>
        <td>进入管理 删除 编辑</td>
    </tr>
    <tr>
        <td><img src="http://localhost/phpmyadmin/themes/pmahomme/img/logo_left.png" style="width:50px;height:50px;"/></td>
        <td>西祠每日精选</td>
        <td>sdfffe1123</td>
        <td>订阅号 <span class="label label-default">未认证</span></td>
        <td>进入管理 删除 编辑</td>
    </tr>
</table>
{% endblock %}
{% block javascript %}
<script>window.currentnav='nav-1';</script>
{% endblock %}