{% extends "main.phtml" %}
{% block content %}
<ol class="breadcrumb">
  <li><a href="<?=$this->url->get('Backend');?>">首页</a></li>
  <li class="active">公众号管理</li>
</ol>

<section class="toolbar">
    <a class='btn btn-primary' href="<?=$this->url->get('Backend/wechat/add');?>">添加公众号</a>
</section>

<table class="table index_wechat_table small">
    <thead>
        <tr>
            <th>Logo</th>
            <th>公众号</th>
            <th>token</th>
            <th>属性</th>
            <th>操作</th>
        </tr>
    </thead>
    {% for item in list %}
    <tr>
        <td><img src="{{ url(item.avatar) }}"/></td>
        <td>{{ item.name }}</td>
        <td>{{ item.token }}</td>
        <td>{% if item.type is '0' %}订阅号{% else %}服务号{% endif %} {% if item.verified is '0' %}<span class="label label-default">未认证</span>{% else %}<span class="label label-success">已认证</span>{% endif %}</td>
        <td><a href="{{ url('Backend/wechat/edit',['id':item.id]) }}">删除</a> <a href="{{ url('Backend/wechat/edit',['id':item.id]) }}">编辑</a></td>
    </tr>
    {% endfor %}
    
</table>
{% endblock %}
{% block javascript %}
<script>window.currentnav='nav-1';</script>
{% endblock %}