<html>
    <head>
        <title>{{ title|default('') }}管理后台</title>
        <link href="http://cdn.bootcss.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
        <link href="http://cdn.bootcss.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
        <link rel="stylesheet" href="<?=$this->url->get('styles/backend/main.css');?>"/>
        {% block css %}{% endblock %}
        <script src="http://cdn.bootcss.com/jquery/2.1.1/jquery.min.js"></script>
    </head>
    <body>
        <header class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">折叠导航</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand">后台</a>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li id='nav-0'><a href="{{ url('Backend/index/index') }}">首页</a></li>
                        <li class="dropdown">
                            <a href="#"  class="dropdown-toggle" data-toggle="dropdown">系统管理<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li id='nav-1'><a href="<?=$this->url->get('Backend/wechat/index');?>">公众号管理</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                                <li class="divider"></li>
                                <li><a href="#">One more separated link</a></li>
                            </ul>
                        </li>
                    </ul>
                    
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b class='text-success'>admin</b> <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="">注销</a></li>
                                <li class="divider"></li>
                                <li><a href="">修改密码</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </header>
        <div class="container">
            {% block content %}{% endblock %}
        </div>
    </body>
    <script src="http://cdn.bootcss.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    {% block javascript %}{% endblock %}
    <script>
        $(function(){
            //菜单状态
            if(window.currentnav){
                $('#'+window.currentnav).addClass('active').parent().parent('.dropdown').addClass('active');
            }
            
        })
    </script>
</html>
